language: bash
dist: xenial

sudo: required

notifications:
  webhooks: https://hook.bearychat.com/=bwBrp/travis/93d020f67c0a20049466b93a0211692c

services:
  - docker

branches:
  only:
    - master
    - dev
    - image

jobs:
  include:
    - stage: deploy
      script:
        - docker build --no-cache -f openapi/server/docker/Dockerfile -t teable/nextoa-openapi --rm=true .
        - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
        - docker push teable/nextoa-openapi
        - docker logout
    - stage: doc
      script:
        - docker build --no-cache -f openapi/server/apidoc/Dockerfile -t teable/nextoa-apidoc --rm=true .
        - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
        - docker push teable/nextoa-apidoc
        - docker logout
    - stage: build
      script:
        - gradlew clean build -x test

stages:
  - name: build
    if: branch = dev
  - name: deploy
    if: branch = image
  - name: apidoc
    if: branch = apidoc
