language: bash
dist: xenial

sudo: required

notifications:
  webhooks: https://hook.bearychat.com/=bwBrp/travis/93d020f67c0a20049466b93a0211692c

services:
  - docker

branches:
  only:
    - master
    - dev
    - image
    - apidoc

jobs:
  include:
    - stage: image
      script:
        - docker build --no-cache -f openapi/server/docker/Dockerfile -t "$API_IMAGE_NAME" --rm=true .
        - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
        - docker push "$API_IMAGE_NAME"
        - docker logout
    - stage: apidoc
      script:
        - docker build --no-cache -f openapi/server/apidoc/Dockerfile -t "$DOC_IMAGE_NAME" --rm=true .
        - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
        - docker push "$DOC_IMAGE_NAME"
        - docker logout
    - stage: build
      script:
        - ./gradlew clean build -x test

stages:
  - name: build
    if: branch = dev
  - name: image
    if: branch = image
  - name: apidoc
    if: branch = apidoc
