version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
