in.clouthink.nextoa.startup.administrator:
  email: admin@clouthink.in
  username: administrator
  cellphone: 13333333333
  password: z@88888888

in.clouthink.nextoa:
  email:
    smtp:
      host: smtp.163.com
      port: 25
      username: istarest@163.com
      password: z@88888888
    sender:
      from: istarest@163.com
      fromAlias: \u661f\u8fb0\u4f73\u529e\u516c\u7f51
      shortUrl: http://117.177.38.55:9999/s/%s
      longUrl: http://117.177.38.55:9999/portal#!//static/app/mobile/paper/detail.html?messageId=%s
    sms:
      key: 300e7a5f999a0c3eebc4fb17afc57092
      secret: 46c1810b
      templateId: 1361355
      endpoint: https://sms.yunpian.com/v2/sms/tpl_single_send.json
      shortUrl: http://117.177.38.55:9999/s/%s
      longUrl: http://117.177.38.55:9999/portal#!//static/app/mobile/paper/detail.html?messageId=%s

logging:
  file:
    name: nextoa.log
    path: .

server:
  port: 8081
  error:
    include-stacktrace: ALWAYS
