in.clouthink.nextoa.startup.administrator:
  email: ${ADMIN_EMAIL:admin@clouthink.in}
  username: ${ADMIN_USERNAME:administrator}
  cellphone: ${ADMIN_MOBILE:13000000000}
  password: ${ADMIN_PASSWORD:Admin_@2020}

